version: '3.8'

services:
  db:
    image: postgres:16.2-alpine
    volumes:
      - ./create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - pg_volume:/var/lib/postgres/data/
    environment:
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASS}"
    ports:
      - '5433:5432'

  cache:
    image: redis:latest
    ports:
      - '6380:6379'

  api:
    build:
      dockerfile: Dockerfile
    depends_on:
      - db
      - cache
    ports:
      - '3000:3000'

volumes:
  pg_volume:
